### ISSUE TITLE
關於{,真,0}傳說關卡的素材最大掉落量

### ISSUE THREAD

**Issue by tzwasd** [battlecatsinfo/battlecatsinfo.github.io#7]
https://github.com/battlecatsinfo/battlecatsinfo.github.io/blob/4c38b74ba0b07b77253c20613e28df49afd33911/stage.js#L776

請問這個最大掉落量是否等於[巴哈文章《傳說關卡貓塔素材掉落機率》](https://forum.gamer.com.tw/C.php?bsn=23772&snA=14848)的抽獎次數及[此表](https://seesaawiki.jp/battlecatswiki/d/%a5%aa%a5%c8%a1%bc%a5%c8%b3%ab%c8%af%c2%e2#content_5_10)的抽選回数？如果是這個意思，那麼當前公式應該有誤，目前我找到了比較準確的公式如下

```js
mM.innerText = `機率(最大掉落量${~~Math.round(info3.mM * info2.mP[star - 1])})`; 
```

**Comment by tzwasd** [comment]
並且存在一個例外，[太古之力Extra關卡](https://battlecatsinfo.github.io/stage.html?s=4-26-0)在[巴哈的文章表格](https://forum.gamer.com.tw/C.php?bsn=23772&snA=14848)中掉落是按4星計算，抽獎次數5，不過我未能驗證其正確性。

**Comment by battlecatsinfo** [comment]
> 並且存在一個例外，[太古之力Extra關卡](https://battlecatsinfo.github.io/stage.html?s=4-26-0)在[巴哈的文章表格](https://forum.gamer.com.tw/C.php?bsn=23772&snA=14848)中掉落是按4星計算，抽獎次數5，不過我未能驗證其正確性。

我沒打過大古之力，所以我不能確定他的是幾星

還有那公式只是我寫時搞混了，`floor(round(multiplier[star] * maxMaterial))` 是沒錯的

**Comment by drocisd** [comment]
> 並且存在一個例外，[太古之力Extra關卡](https://battlecatsinfo.github.io/stage.html?s=4-26-0)在[巴哈的文章表格](https://forum.gamer.com.tw/C.php?bsn=23772&snA=14848)中掉落是按4星計算，抽獎次數5，不過我未能驗證其正確性。

太古之力（EX）(4026-00)是被當作1星處理的，且掉落內容也有別於太古之力（4星）(0048-00)，詳情參見Data/Map_option以及Data/DropItem

**Comment by tzwasd** [comment]
> > 並且存在一個例外，[太古之力Extra關卡](https://battlecatsinfo.github.io/stage.html?s=4-26-0)在[巴哈的文章表格](https://forum.gamer.com.tw/C.php?bsn=23772&snA=14848)中掉落是按4星計算，抽獎次數5，不過我未能驗證其正確性。
> 
> 太古之力（EX）(4026-00)是被當作1星處理的，且掉落內容也有別於太古之力（4星）(0048-00)，詳情參見Data/Map_option以及Data/DropItem

應該是超絕搞錯了，然後巴哈文章作者照抄了超絕（其他來源沒有標註太古之力（EX）的掉落）
